{% set name = "napari-filaments" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari_filaments-{{ version }}.tar.gz
  sha256: 3b8a6c2f21efa7a24f760ba561e42ac06772a75f6e773f2cd89e723f4ac919ad

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  script_env:
    - QT_QPA_PLATFORM=offscreen

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - importlib_metadata
    - macro-kit
    - magic-class >=0.7.3
    - magicgui
    - matplotlib-base
    - napari
    - numpy
    - pandas
    - psygnal
    - python >={{ python_min }}
    - qtpy
    - scipy

test:
  imports:
    - napari_filaments
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://github.com/hanjinliu/napari-filaments
  summary: A napari plugin for filament analysis
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - hanjinliu
    - jaimergp
